spring.config.import=optional:file:.env[.properties]

# Server
server.port=${APP_PORT:8080}

# MongoDB
spring.data.mongodb.uri=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:${MONGO_PORT:27017}/${MONGO_DB}?authSource=admin

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Default Admin
admin.name=${ADMIN_NAME:Admin}
admin.email=${ADMIN_EMAIL:admin@letsplay.ma}
admin.password=${ADMIN_PASSWORD:admin123}

# Logging
logging.level.org.springframework.security=WARN
logging.level.ma.zone01.letsplay=DEBUG
