spring.config.import=optional:file:.env[.properties]

# Server
server.port=${APP_PORT}
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=letsplay

# MongoDB
spring.data.mongodb.uri=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:${MONGO_PORT:27017}/${MONGO_DB}?authSource=admin

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Default Admin
admin.name=${ADMIN_NAME:Admin}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

# Logging
logging.level.org.springframework.security=WARN
logging.level.ma.zone01.letsplay=DEBUG
